### ISSUE TITLE
PHP notice when new block instance created and not configured yet

### ISSUE THREAD

**Issue by mudrd8mz** [limsko/moodle-block_slider#1]
Please make sure you have debugging mode on when developing Moodle plugins. When I add a new instance of the block into the course, I am getting

```
Notice: Trying to get property of non-object in /blocks/slider/block_slider.php on line 48
```

as I think there is no `$this->config` yet.

**Comment by limsko** [comment]
Ok, I will give more focus on testing with debugging.

I forget first to check if $this->config->text is not empty.
Fixed in 0.1.1.
