### ISSUE TITLE
Pagination button stay visible when disabled under configuration

### ISSUE THREAD

**Issue by johnnylupino** [limsko/moodle-block_slider#10]
Hi, 

While checking the extra plugin configuration settings, I found out that
when the 'Pagination' check-box is disabled under block's configuration, the buttons are still visible in the block's footer (checked on Dashboard/Front Page and inside a course)

Moodle version:3.5.6
Plugin version: 2018062901

Regards,
Archie

**Comment by limsko** [comment]
Hello,
I have fixed this issue in 0.2.1. 
Best regards,
Kamil
