### ISSUE TITLE
Auto-play running when disabled under configuration

### ISSUE THREAD

**Issue by johnnylupino** [limsko/moodle-block_slider#11]
Hi,

It looks like the auto-play functionality, when disabled under the block's setting can still be running.
I triggers the correct behavior (stops running ) when I click on Prev/Next button.
Steps to reproduce:
-disable Auto-play under the settings and save (ensure Navigation check-box is enabled)
-turn editing OFF
-the slider will be still in auto-play mode unless user click the Prev/Next buttons

Moodle version:3.5.6
Plugin version: 2018062901

Regards,
Archie

**Comment by limsko** [comment]
Hello,
I have fixed this issue in 0.2.1. 
Best regards,
Kamil
