### ISSUE TITLE
Invalid way of including the FontAwesome CSS

### ISSUE THREAD

**Issue by mudrd8mz** [limsko/moodle-block_slider#4]
I believe that the `<link>` tag that loads the fontawesome is not valid inside the `<body>` tag in this form. According to the [HTML5 spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-link-element) and [this stackoverflow question](http://stackoverflow.com/questions/4957446/load-external-css-file-in-body-tag), it is a bit more complicated (even if it may work in browsers).

I believe that `$this->page->requires->css()` would be a better option here.

**Comment by limsko** [comment]
I've deleted it in 0.1.1 version. Moodle has icons for navigation in clean theme so FontAwesome was only taking load.
