### ISSUE TITLE
Use API to get the list of images to display

### ISSUE THREAD

**Issue by mudrd8mz** [limsko/moodle-block_slider#5]
It is always wise to use an API (if there is one) instead of relying on the internal implementation details. I think that instead of trying to load the list of files (images) via direct SQL, it would be better to use https://docs.moodle.org/dev/File_API#List_area_files

Similarly, instead of computing the actual file URL yourself, the `moodle_url::make_file_url()` method (illustrated at the docs page linked above) should be used.

**Comment by limsko** [comment]
Now im using API to get and display files. I'm still learning Moodle. Much Thanks!
