### ISSUE TITLE
Not found error after clicking on the setting

### ISSUE THREAD

**Issue by mikeross6233m** [limsko/moodle-block_slider#7]
When I go in the settings of slider block it just shows the message " 404Not Found".
![screenshot from 2015-12-01 11 48 41](https://cloud.githubusercontent.com/assets/14011478/11493756/d85b42a2-9821-11e5-8ff1-1904ca231ad7.png)

I think you are missing the setting.php file in the plugin

**Comment by limsko** [comment]
Hi,

You have right.
I need to change:

function has_config() {
         return _true_;
}

to:

function has_config() {
         return _false_;
}

Thanks for submitting this issue.

W dniu 2015-12-01 o 07:22, mikeross6233m pisze:

> When I go in the settings of slider block it just shows the message " 
> 404Not Found".
> screenshot from 2015-12-01 11 48 41 
> https://cloud.githubusercontent.com/assets/14011478/11493756/d85b42a2-9821-11e5-8ff1-1904ca231ad7.png
> 
> I think you are missing the setting.php file in the plugin
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/limsko/moodle-block_slider/issues/7.

## 

Pozdrawiam
Kamil Łuczak

**Comment by limsko** [comment]
Hello,
I have fixed this issue in 0.2 version. 
Best regards,
Kamil
