### ISSUE TITLE
MOODLE_INTERNAL check

### ISSUE THREAD

**Issue by OlenaTatarintseva** [limsko/moodle-block_slider#9]
Hello,

First of all I want say thank you for your work with the plugin.

I just would like to suggest, that it would be good to add MOODLE_INTERNAL check in php files in the plugin. 

Best regards,
Olena Tatarintseva

**Comment by limsko** [comment]
Hi!
Thanks for your interest Olena. I have fixed this issue in new version - 0.2 - released today.
